### PR TITLE
Update to milestone dependencies

### PR DESCRIPTION
**Pull request by melix**

### CODE REVIEW

**Comment by radovanradic** [comment]
> @melix could you look into the failures of this PR ? https://github.com/micronaut-projects/micronaut-test-resources/actions/runs/4608497488/jobs/8144336667?pr=196

I think this is due to hibernate and hibernate reactive dependencies in data and sql.
We updated micronaut-sql dependency to

```
managed-hibernate = "6.2.0.Final"
managed-hibernate-reactive = "2.0.0.Beta1"
```
and I think it is in 5.0.0-SNAPSHOT but not in M1 which is being pulled here.
test-resources is pulling micronaut-data but getting  hibernate reactive alpha currently and hibernate final. Probably sql M2 should be built so we can update data and pull correct dependencies.

**Comment by sdelamo** [comment]
HiveMQ failed https://ge.micronaut.io/s/vhuiwrcqzmgge

**Comment by melix** [comment]
mmm, this seems to be a new regression, I'll take a look.

**Comment by melix** [comment]
Seems that I have to add an `application-test.yml` file with the following contents now:

```yaml
mqtt:
  client:
    client-id: ${random.uuid}
```

And then the test passes. I guess something has changed in our MQTT support which mandates this now.

**Pull request merged**
