### PR TITLE
Fix java 21 build

### PR DESCRIPTION
**Pull request by wetted**
Supersedes #415 to stop micronaut-build force pushing it all the time

### CODE REVIEW

**Comment by timyates** [comment]
Looks like this has been failing for a while https://ge.micronaut.io/scans/tests?search.timeZoneId=Europe%2FLondon&tests.container=io.micronaut.testresources.server.TestResourcesControllerTest&tests.test=verifies%20that%20server%20can%20instantiate%20container

**Comment by timyates** [comment]
I've reverted that commit.  An import wasn't required (as the class is in the same package) and the commit changed the class that was returned to the wrong one

**Comment by timyates** [comment]
This test seems to hang under Java 21 🤔 

https://github.com/micronaut-projects/micronaut-test-resources/blob/5917a0e28849dcade97bd5042a85a4a1c4b1d114/test-resources-server/src/test/groovy/io/micronaut/testresources/server/TestResourcesControllerTest.groovy#L79

@melix any ideas?

**Comment by melix** [comment]
No I don't.

**Comment by timyates** [comment]
Found it...  PR incoming...  Lock issue I think

**Comment by timyates** [comment]
Ok, so the issue was that under Java 21 the controller switches to using virtual executors.

Inside TestContainers we use a re-entrant lock and this all worked as it was effectively the same thread making all the requests

But with Java 21, we're seeing a new thread per request, and this is causing issues

I *think* this is fixed by ensuring all LOCK/UNLOCK couplets are in a try...finally

We could also force java 17 behavior by using `@ExecuteOn(IO)` in the controller methods...

But I think checking the locks are unlocked is the more correct behavior...

**Review by melix — APPROVED** [review]

**Pull request merged**
