### PR TITLE
(feat) add Localstack SNS

### PR DESCRIPTION
**Pull request by lucjross-favor**
This adds a Localstack SNS provider.

I tried to create a test for subscription & notification functionality that used a test HTTP controller, but that proved difficult for Docker/host networking reasons. The test now just makes sure that the create-topic operation works.

### CODE REVIEW

**Comment by lucjross-favor** [comment]
Also, (a) is this the right branch to merge into? and (b) could you say how soon this could go into a release?

Thanks!

**Comment by lucjross-favor** [comment]
> Execution failed for task ':micronaut-test-resources-localstack-sns:findBaseline'.
> > Could not find a previous version for 2.6.0

How do I fix this?

**Comment by lucjross-favor** [comment]
Hi @melix , could you advise on the above? 🙏

**Comment by melix** [comment]
> How do I fix this?

You need to add:

```gradle
micronautBuild {
    binaryCompatibility {
        enabledAfter '2.6.0'
    }
}
```

in the new module's build.gradle file

**Comment by melix** [comment]
Thanks for your contribution!

**Pull request merged**
