### PR TITLE
Workaround for shutdown error

### PR DESCRIPTION
**Pull request by melix**
This commit is a workaround for an error which seems to happen since the upgrade to Micronaut 4.6. In a nutshell, when the `/stop` endpoint is called, the thread which was started to monitor if the service is properly shutdown after a timeout was started and the application context was closed, _before_ the `stop` method would return something to the client. As a consequence, there was an error message saying that the application context wasn't open and that a bean (the message writers) weren't found. This was not quite true, since the application context _used to be_ open but wasn't.

The workaround, which isn't great, is to use the task scheduler to delay the shutdown by a few hundreds of milliseconds. This gives the opportunity to send the response back to the client _before_ the application context is shutdown.

Note that in any case, this wasn't a big issue, since the service would be shutdown anyway, but the error message for the user wasn't great.

### CODE REVIEW

**Review by alvarosanchez — APPROVED** [review]
Does this deserve any further investigation in core? @yawkat @dstepanov @graemerocher

**Comment by dstepanov** [comment]
In 4.6 @graemerocher added a check to prevent accessing the bean context when it's shutdown. 
Which code is trying to access the context after it's been shutdown or in process?

**Comment by graemerocher** [comment]
correct. The context used to be more forgiving in terms of allowing access to beans even after shutdown. That is no longer the case and it was a bug that it was possible. That said this seems to be related to our lack of proper support for graceful shutdown which needs to be correctly ideally in 4.7

**Comment by alvarosanchez** [comment]
So then, should this logic be handled with a server shutdown event listener, instead of a custom controller method?

**Comment by graemerocher** [comment]
not sure how an event listener would help

**Pull request merged**
