### PR TITLE
test runtime jackson databind

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by melix** [comment]
Why is this needed now?

**Comment by sdelamo** [comment]
test failed for me locally without it. No JsonMapper implementation.

**Comment by melix** [comment]
Interesting, maybe we got that dependency transitively before?

**Comment by sdelamo** [comment]
> Interesting, maybe we got that dependency transitively before?

🤷‍♂️Do test pass for you without it?

**Comment by melix** [comment]
I haven't tested, I just assumed that one PR was merged which introduced a breaking change in the tests.

**Pull request closed without merging**
